# General MkDocs project settings
site_name: Soveren Documentation
site_description: Explore our guides and examples for integrating Soveren into your production environment
site_url: https://docs.soveren.io/en/stable/

# Navigation tree
nav:
  - Home: 'index.md'
  - Quick start: 'getting-started/quick-start.md'
  - Administration:
      - Managing Users: 'administration/managing-users.md'
      - Managing Sensors: 'administration/managing-sensors.md'
      - Configuring the Sensor: 'administration/configuring-sensor.md'
      - Securing the Sensor: 'administration/securing-sensor.md'
      - Troubleshooting the Sensor: 'administration/troubleshooting-sensor.md'
  - User guide:
      - Overview: 'user-guide/overview.md'
      - Sensitive data model: 'user-guide/data-model.md'
  - Integration:
      - Jira: 'integration/jira.md'
      - Slack: 'integration/slack.md'
      - Webhook: 'integration/webhook.md'
      - Event objects: 'integration/event-objects.md'
      - Object API: 'integration/api/object-api.md'
  - Architecture:
      - Overview: 'architecture/overview.md'
      - Requirements and recommendations: 'architecture/infrastructure-fit.md'
      - Capturing the traffic: 'architecture/traffic-interception.md'
      - Processing the traffic: 'architecture/traffic-processing.md'
      - Kubernetes metadata: 'architecture/k8s-metadata.md'
      - Sensitive data detection: 'architecture/detection.md'

# Theme settings, refer to https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
theme:
  name: material
  # Override default theme templates; so far removed the prev-next buttons frame from the footer.
  custom_dir: customize
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: deep purple
      accent: deep purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: deep purple
      accent: deep purple
  logo: img/logos/logo-simple-white.svg
  favicon: img/favicons/favicon-app-black.svg
  features:
    - navigation.top
    - navigation.indexes
    - navigation.prune
    - navigation.tabs
#    - navigation.tracking
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

# Extensions
markdown_extensions:
  # Hover-overs for abbreviation for context-like glossary
  - abbr
  - tables
  # Notes, tips, warnings, etc.
  - admonition
  - pymdownx.blocks.details
  # Content tabs
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Add HTML attributes and CSS classes to any Markdown element
  - attr_list
  # Write Markdown inside HTML
  - md_in_html
  - def_list

# Redefining the theme and other elements, like panels, via custom .css styles
extra_css:
  - stylesheets/extra.css

# Custom JS scripts
extra_javascript:
  - js/analytics.js
  - js/current-year.js

extra:
  # Disable the "Build with MkDocs Material" line in the footer
  generator: false

# Copyright text in the footer
copyright: Copyright &copy; <span id="current-year">2023 —</span><span id="year-dash"></span> Soveren, Inc.<div id="readthedocs-embed-flyout">&nbsp;</div>

plugins:
  - search
  - glightbox
  - open-in-new-tab
